[project]
name = "presentations-with-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepeval>=4.2.3",
    "dotenv>=0.9.9",
    "faker>=40.39.0",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.8",
    "jupyterlab-widgets>=3.0.17",
    "langchain>=1.4.0",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.6.2",
    "langchain-tavily>=0.2.18",
    "langchainhub>=0.1.21",
    "langgraph>=1.2.11",
    "nbconvert>=7.17.1",
    "openai>=2.53.0",
    "pydantic>=2.13.4",
    "syntok>=1.4.4",
    "tavily-python>=0.8.3",
    "tiktoken>=0.14.0",
    "watchdog>=6.0.0",
]
